# Семинар 1: знакомство с NumPy


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [1]:
2 + 2

4

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [2]:
import numpy as np

In [22]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [17]:
vec

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [18]:
print(vec)

[[[1 2]
  [3 4]
  [5 6]]]


С чем мы работаем?

In [19]:
vec.dtype

dtype('int64')

In [13]:
type(vec)

numpy.ndarray

Размер массива:

In [23]:
vec.shape

(3, 2)

Число осей:

In [24]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [25]:
np.sum(vec)

21

In [26]:
np.sum(vec, axis=0)

array([ 9, 12])

In [27]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [28]:
vec.sum()

21

Транспонируем массив:

In [30]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [31]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [36]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [34]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [40]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
vec[:, 1]

array([2, 4, 6])

In [45]:
vec[2, :]

array([5, 6])

In [58]:
vec[1:2, 0]

array([3])

In [61]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [67]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [63]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [68]:
vec**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [69]:
vec + vec**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [70]:
vec * vec**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [71]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [73]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
vec.dot(vec**2)

ValueError: ignored

In [74]:
vec.dot((vec**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [75]:
vec @ (vec**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [76]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [79]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [81]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [83]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [84]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [86]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [ ]:
np.zeros((2, 3))

Массив из единиц:

In [ ]:
np.ones((3, 2))

Единичная матрица:

In [ ]:
np.identity(5)

Массивы можно объединять:

In [87]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [89]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [94]:
np.random.rand(2, 3)

array([[0.20112905, 0.88601087, 0.51361992],
       [0.57830159, 0.29928265, 0.8371974 ]])

In [112]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [115]:
np.random.randn(3, 2)

array([[ 0.84593044, -0.50354158],
       [-0.96333553,  0.06496863],
       [-3.20504023,  1.05496943]])

In [121]:
np.random.normal(2, 1, size=3)

array([1.22494344, 1.02089605, 0.45063706])

In [123]:
np.random.randint(5, 10, size=3)

array([6, 5, 9])

Почему вообще используют `numpy`?

In [125]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [126]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 26.1 s, sys: 0 ns, total: 26.1 s
Wall time: 26.8 s


In [127]:
%%time
C = A @ B

CPU times: user 5.85 ms, sys: 0 ns, total: 5.85 ms
Wall time: 7.03 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [146]:
arr = np.array([1, 2, 3, 4, 5])

In [147]:
# 1
arr[::-1]

array([5, 4, 3, 2, 1])

In [143]:
# 2
arr[arr % 2 == 1].max()

5

In [148]:
# 3
arr[arr % 2 == 1] = 45
arr

array([45,  2, 45,  4, 45])

In [150]:
# 4
n = 10
np.arange(1, n * 2, 2)[::-1]

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [156]:
# 5
arr = np.array([1, 2, 3, 4, 5])
num = 1.6
diff = np.abs(arr - num)
print(f"closest: {arr[np.argmin(diff)]}, farthest: {arr[np.argmax(diff)]}")

closest: 2, farthest: 5


In [216]:
# 6
arr = np.array([4, 6, 0, 1])
antiderivative = np.poly1d(np.array([4, 6, 0, 1])).integ().coefficients
antiderivative[-1] = -2
antiderivative

array([ 1.,  2.,  0.,  1., -2.])

In [220]:
# derivative
point = 5
arr = antiderivative

derivative = np.poly1d(arr).deriv()
print(derivative)
derivative(point)

   3     2
4 x + 6 x + 1


651.0